### ISSUE TITLE
数据更新，动态修改容器size，会导致内部item的坐标获取异常

### ISSUE THREAD

**Issue by CASTROCC** [icipiqkm/UISuperScrollView#4]
您好，我在数据更新的时候动态修改了Layout和scrollView的宽度或者高，我想让数据长度为1的时候item按照居中排列(layout 和 scrollview 的锚点都为0.5)，但是当list更新的时候，item的坐标位置获取发生了偏移

**Comment by icipiqkm** [comment]
你提供下重现步骤吧 最好能提供偏移的图

**Comment by CASTROCC** [comment]
![image](https://user-images.githubusercontent.com/27627567/109147804-69e4b100-77a0-11eb-8b08-7a66ae6ab89c.png)
当我在外部改变容器的size的同时，我调用了onChangePosition方法刷新了布局，然后问题就解决了。。

**Comment by icipiqkm** [comment]
👌 牛逼

**Comment by icipiqkm** [comment]
1
